package graphics.inventory;

import game.combat.ArmorItem;
import java.awt.Container;
import java.awt.Dimension;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import misc.Tools;

public class ArmorItemPanel extends DataPanel {

	private ArmorItem armorItem;

	public ArmorItemPanel(ArmorItem armorItem, ContainerItemPanel parent) {
		super(parent);
		this.armorItem = armorItem;
		initComponents();
		adjustSize();
	}

	@Override
	public void updateValues() {
		armorItem.setName(nameTextField.getText());
		Integer armor = Tools.getNonNegativeIntegerFromTextField(armorTextField,
				"Rüstungswert", this);
		if (armor != null) {
			armorItem.setArmor(armor);
		}
		Integer strain = Tools.getNonNegativeIntegerFromTextField(
				strainTextField, "Belastung", this);
		if (strain != null) {
			armorItem.setStrain(strain);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        staticLabelArmor = new javax.swing.JLabel();
        armorTextField = new javax.swing.JTextField();
        staticLabelStrain = new javax.swing.JLabel();
        strainTextField = new javax.swing.JTextField();

        setAlignmentY(0.0F);

        nameTextField.setColumns(20);
        nameTextField.setText(armorItem.getName());

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/trash.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        staticLabelArmor.setText("RS:");

        armorTextField.setColumns(3);
        armorTextField.setText(String.valueOf(armorItem.getArmor()));

        staticLabelStrain.setText("BE:");

        strainTextField.setColumns(3);
        strainTextField.setText(String.valueOf(armorItem.getStrain()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staticLabelArmor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(armorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staticLabelStrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(staticLabelArmor)
                        .addComponent(armorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(staticLabelStrain)
                        .addComponent(strainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
		armorItem.getContainer().remove(armorItem);
		parent.removeSubPanel(this);
		parent.revalidate();
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField armorTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel staticLabelArmor;
    private javax.swing.JLabel staticLabelStrain;
    private javax.swing.JTextField strainTextField;
    // End of variables declaration//GEN-END:variables
}
