package graphics.inventory;

import game.combat.MeleeWeaponItem;
import java.awt.Dimension;

public class MeleeWeaponItemPanel extends DataPanel {

	private MeleeWeaponItem meleeWeaponItem;

	public MeleeWeaponItemPanel(MeleeWeaponItem meleeWeaponItem,
			ContainerItemPanel parent) {
		super(parent);
		this.meleeWeaponItem = meleeWeaponItem;
		initComponents();
		adjustSize();
	}

	@Override
	public void updateValues() {
		meleeWeaponItem.setName(nameTextField.getText());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTextField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        staticLabelCombatTechnique = new javax.swing.JLabel();
        staticLabelDamage = new javax.swing.JLabel();
        damageTextField = new javax.swing.JTextField();
        staticLabelMod = new javax.swing.JLabel();
        modTextField = new javax.swing.JTextField();
        staticLabelRange = new javax.swing.JLabel();
        rangeTextField = new javax.swing.JTextField();
        combatTechniqueLabel = new javax.swing.JLabel();

        setAlignmentY(0.0F);

        nameTextField.setColumns(20);
        nameTextField.setText(meleeWeaponItem.getName());

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/trash.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        staticLabelCombatTechnique.setText("Kampftechnik:");

        staticLabelDamage.setText("TP:");

        damageTextField.setColumns(5);
        damageTextField.setText(meleeWeaponItem.getDamage());

        staticLabelMod.setText("AT/PA Mod:");

        modTextField.setColumns(3);
        modTextField.setText(meleeWeaponItem.getMod());

        staticLabelRange.setText("Reichweite:");

        rangeTextField.setColumns(5);
        rangeTextField.setText(meleeWeaponItem.getRange());

        combatTechniqueLabel.setText(meleeWeaponItem.getType().getCombatTechnique());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staticLabelDamage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(damageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staticLabelMod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staticLabelRange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staticLabelCombatTechnique)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combatTechniqueLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteButton)
            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(staticLabelCombatTechnique)
                .addComponent(staticLabelDamage)
                .addComponent(damageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(staticLabelMod)
                .addComponent(modTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(staticLabelRange)
                .addComponent(rangeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(combatTechniqueLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
		meleeWeaponItem.getContainer().remove(meleeWeaponItem);
		parent.removeSubPanel(this);
		parent.revalidate();
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel combatTechniqueLabel;
    private javax.swing.JTextField damageTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField modTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField rangeTextField;
    private javax.swing.JLabel staticLabelCombatTechnique;
    private javax.swing.JLabel staticLabelDamage;
    private javax.swing.JLabel staticLabelMod;
    private javax.swing.JLabel staticLabelRange;
    // End of variables declaration//GEN-END:variables
}
